### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by timur-sh** [timur-sh/queryman-builder#31]
- [x]  Expression [#53](https://github.com/timur-sh/queryman-builder/issues/53)
- [x]  UPDATE statement [#52](https://github.com/timur-sh/queryman-builder/issues/52)
- [x]  INSERT statement [#41](https://github.com/timur-sh/queryman-builder/issues/41)
- [x]  Documentation for conditions [#40](https://github.com/timur-sh/queryman-builder/issues/40)
- [x]  Documentation for CREATE SEQUENCE [#39](https://github.com/timur-sh/queryman-builder/issues/39)
- [x]  Documentation for SELECT [#30](https://github.com/timur-sh/queryman-builder/issues/30)
